version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "pass"
      MONGO_INITDB_DATABASE: stark
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb:/data/db
    networks:
      - default
  node:
    build: .
    container_name: node
    restart: always
    environment:
      - MONGODB_URL=mongodb://root:pass@mongodb:27017 # mongodb link
      - GRAPHQL_URL=https://starkscan-v2.stellate.sh/ # url for parse
      - PROXY= # rotate proxy
      - SLOW_MODE=false # slow mode for parse new/all contracts
      - PARSE_ALL_CONTRACTS=false # parse old contracts for db
      - NEW_INSERT_CONTRACTS=true # insert new contracts using 30m timer
      - UPDATE_CONTRACTS=true # update every 6h all contracts for db
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
      - ./client:/node/client
      - ./server:/node/server
    networks:
      - default
networks:
  default:
